port 6380
cluster-enabled yes
cluster-config-file nodes.conf
cluster-node-timeout 5000
cluster-announce-ip redis-node-2
cluster-announce-port 6380
cluster-announce-bus-port 16380
appendonly yes
dir /data